version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: sample
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
  go:
    image: web-service-gin_go:latest
    volumes:
      - ".:/app"
    tty: true
    ports:
      - 8080:8080
    depends_on:
      db:
         condition: service_healthy
volumes:
  db-data: