version: "3"
services:
  # db:
  #   image: mysql:8.0
  #   # command: rm -rf /var/lib/mysql/*
  #   environment:
  #      MYSQL_USER: ${MYSQL_USER}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #      MYSQL_DATABASE: ${MYSQL_DATABASE}
  #   ports:
  #     - 3306:3306
  #   restart: always
  #   volumes:
  #     - db-data:/var/lib/mysql
  #     - ./sql:/docker-entrypoint-initdb.d
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
    volumes:
      - db-data:/var/lib/postgresql/data
  go:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: web-service-gin_go:latest
    volumes:
      - ".:/build"
    tty: true
    depends_on:
      - db
  prd:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: web-service-gin_prd:latest
    environment:
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: /bin/sh -c "/app/main"
volumes:
  db-data: